[workspace]
members = ["egui-stylist", "egui-theme", "egui-stylist-native"]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]
egui = { git = "https://github.com/setzer22/egui/", branch = "setzer22/my-fork" }
